-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgeraPIpi19RsOl9gG
as5Ur6iapsKBlkWQO2EEi914tlqgCgYIKoZIzj0DAQehRANCAAT2w9/VwuhcKxjg
gHuO1JAR0bz+SJHUknhagA9VtE806hvaNeaGFcRbHomBFJSzd4bPAnaHK8lHEqLJ
iaxWsTAW
-----END PRIVATE KEY-----